config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :chatrooms
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
  validates :body, presence: true

  scope :latest_messages, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :chatrooms, through: :messages
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15 }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?

    redirect_to login_path
    flash[:error] = 'You must be logged in to perform that action.'
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: :show
  before_action :require_user, only: :show

  def index
    @chatrooms = Chatroom.paginate(page: params[:page], per_page: 5).order(topic: :asc)

  end

  def show
    @message = Message.new
    @messages = @chatroom.messages.latest_messages
  end

  private

  def set_chatroom
    @chatroom = Chatroom.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = Message.new(message_params)
    message.user = current_user
    if message.save
      ActionCable.server.broadcast 'chatroom_channel',
        mod_message: message_render(message)
      head :ok
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :chatroom_id)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to chatrooms_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :check_if_logged_in?, except: [:destroy]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'Logged in successfully'
      redirect_to root_path
    else
      flash.now[:error] = 'There was something wrong with your login credentials.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logged out'
    redirect_to login_path
  end

  private

  def check_if_logged_in?
    return unless logged_in?

    flash[:error] = 'You are already logged in.'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in?, only: [:new]

  def index
    @users = User.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Hey #{@user.username}!  Welcome to Message Me."
      redirect_to root_path
    else
      flash.now[:error] = 'There was something wrong while Sign Up.'
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def check_if_logged_in?
    return unless logged_in?

    flash[:error] = 'You are already logged in.'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/views/chatrooms/index.html.erb
<h1 class="ui center aligned header">
  Message Me Chatrooms
</h1>

<%= will_paginate @chatrooms, renderer: WillPaginateSemanticUi::ActionView::Renderer %>

<table class="ui celled table">
  <thead>
    <tr><th>Topic</th>
    <th>Messages</th>
  </tr></thead>
  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td data-label="Username"><%= link_to chatroom.topic, chatroom_path(chatroom)%></td>
        <td data-label="Messages"><%= chatroom.messages.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/chatrooms/show.html.erb
<div class="row col-md-8 col-md-offset-2">
  <h1><%= @chatroom.topic %></h1>

<div class="panel panel-default">
  <div class="ui fluid raised card chatbox">
    <div class="content", id="messages">
      <div class="ui feed", id="chatromm_container" >
        <div class="event">
          <div class="content">
            <% @messages.each do |message| %>
              <%= render partial: 'messages/message', locals: { message: message } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |message_type, message_content| %>
    <div class="ui <%= message_type %> message transition">
      <i class="close icon"></i>
      <div class="header">
        <%= message_content %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatrooms", chatrooms_path, class: "item"%>
<%= link_to "Friends", users_path, class: "item"%>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to 'Logout', logout_path, class: 'item', method: :delete %>
      <% else %>
        <%= link_to "Log in", login_path, class: "item"%>
      <% end %>
    </div>
  </div>
  <% unless logged_in? %>
    <div class="item">
        <%= link_to 'Sign Up', signup_path, class: 'ui orange button' %>
    </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui teal inverted small menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<p><strong><%=message.user.username%>: </strong> <%=message.body%></p>

app/views/messages/_message_form.html.erb
  <div class="extra content">
    <%= form_for(message, html: {class: 'ui reply form', role: 'form'}, url: message_path, remote: true) do |f| %>
      <div class="field">
        <%= f.label :your_message %>
        <div class="ui fluid icon input">
          <%= f.text_field :body %>

          <%= f.hidden_field :chatroom_id, value: chatroom.id %>
          <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<h1 class="ui center aligned header">
  Welcome to MessageMe
</h1>
<h2 class="ui center aligned icon header">
  <i class="circular orange comments icon"></i>
  You can see the rooms or users in the navigation bar<br>
  If you want to interact, you just have to sign up
</h2>

app/views/users/_form.html.erb
<div class="ui placeholder segment">
  <div class="ui ">
    <div class="column">
      <%= form_with(model: user, class: "ui form", local: true) do |form| %>
        <div class="field">
          <%= form.label :username, 'Username' %>
          <div class="ui left icon input">
            <%= form.text_field :username, placeholder: 'Username' %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= form.label :password, 'Password' %>
          <div class="ui left icon input">
            <%= form.password_field :password, placeholder: 'Enter your password' %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= form.submit "Sign Up", class: "ui orange submit button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card shadow mb-5 bg-white rounded text-center">
      <div class="card-header font-italic">
        <%= link_to user.username, user, class: "header-link" %>
      </div>
      <div class="card-body">
        <%= link_to "View profile", user, class: "btn btn-outline-info"%>
      </div>
      <div class="card-footer text-muted">
        <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1 class="ui center aligned header">
  Message Me Friends
</h1>

<%= will_paginate @users, renderer: WillPaginateSemanticUi::ActionView::Renderer %>

<table class="ui celled table">
  <thead>
    <tr><th>Username</th>
    <th>Sent messages</th>
  </tr></thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td data-label="Username"><%= user.username %></td>
        <td data-label="Messages"><%= user.messages.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1 class="ui center aligned header">
  Sign Up for Message Me
</h1>
<h1 class="ui center aligned medium icon header">
  <i class="circular orange comments icon"></i>
</h1>

<%= render 'form', user: @user %>